---
title: "Percentage of Population Living Under 2011 PPP$ 1.90 per Day"
output:
  github_document: default
  html_notebook: default
---


```{r setup}
library(tidyverse)
library(lubridate)
```

```{r}
Sys.which("python")         # "/usr/bin/python" ...which doesn't connect the API, in my setup
                            # ...So specify use of the `anaconda3` version

library(reticulate)
use_python("/Users/markbeveridge/anaconda3/bin/python")

py_config()                 # (Couldn't find this function when using "/usr/bin/python")
Sys.which("python")         # Different answer. (So now can remove `engine.path="/Users/markbeveridge/anaconda3/bin/python"` from python chunk headers)
```


# Percentage of Population Living Under 2011 PPP$ 1.90 per Day
## Data import

Connect to data at https://apihighways.org/data-sets/6a6de0b8-e544-495a-93ab-e8bc3c59fb20

API code copied from the apihighways page for this dataset :

```{python}
import http.client

conn = http.client.HTTPSConnection("api.apihighways.org")

conn.request("GET", "/query?sql=SELECT%20*%20FROM%206a6de0b8-e544-495a-93ab-e8bc3c59fb20")

res = conn.getresponse()
data = res.read()

# print(data.decode("utf-8"))                     # Don't need/want to print all the data

# ----------
# Currently unable to share state across Python chunks [https://support.rstudio.com/hc/en-us/community/posts/222207188-Multiple-Python-chunks-in-RStudio-R-Markdown], "we're hoping to make some improvements for this in RStudio 1.2". Which means a 2nd chunk wouldn't be able to use the `data` from this one. (It does work if all the code is in a single chunk)
# ----------
# To overcome that, installed **reticulate** package, which should make it possible to share ...but doesn't work for me, below, when I try to call `data` in another python chunk. (I tried both running and knitting). cf. [https://stackoverflow.com/questions/49503195/reticulate-running-python-chunks-in-rmarkdown] ; [https://github.com/yihui/knitr/issues/1440] ; [https://github.com/rstudio/reticulate/pull/107]
```

```{python}
# "If you add this code it might be useful in parsing the JSON into a Python dictionary" :
import json
j = json.loads(data)

print(j['data'][0])

# This code is just temporary, to check that variables persist across chunks. (Then it will be deleted, and pandas/ dplyr used.) BUT it DOESN'T work
```



## xxx

```{r}
ggplot(py$data, aes(year, value-1)) +
  geom_point()

# This code won't work, because ggplot won't accept data in the form of a list of python dictionaries. BUT it doesn't get that far. The error is `object 'py' not found`, which implies that `data` won't work across chunks, even as a dataframe
```

